server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root

  security:
    username: root
    password: root


